fixes messy quotes with HEREDOC syntax

diff --git a/.github/workflows/blue-green-deployment.yaml b/.github/workflows/blue-green-deployment.yaml
--- a/.github/workflows/blue-green-deployment.yaml
+++ b/.github/workflows/blue-green-deployment.yaml
@@ -21,43 +21,52 @@ jobs:
 
     - name: Connect to SSH and Deploy
       run: |
-        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} '
-          ###############################
-          # Begin Blue-Green Deployment #
-          ###############################
+        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} <<"SSHCONN"
+        ###############################
+        # Begin Blue-Green Deployment #
+        ###############################
 
-          # determine which PM2 app is currently idle
-          current=$(pm2 describe [blue]my-repo-name | grep "status" | head -n 1 | awk '"'"'{print $4}'"'"' )
-          if [ "$current" == "online" ]; then
-            active_app="blue"
-            active_port="3001"
-            idle_app="green"
-            idle_port="3002"
-          else
-            active_app="green"
-            active_port="3002"
-            idle_app="blue"
-            idle_port="3001"
-          fi
+        echo "Pre-Deplay Active Port: $active_port"
+        echo "Pre-Deploy Idle Port: $idle_port"
 
-          # build the idle app - exit on failure
-          cd /srv/www/production/my-repo-name-$idle_app
-          git pull
-          npm install
-          if ! npm run build; then
-            echo "Build failed on my-repo-name-$idle_app."
-            exit 1
-          fi
+        # determine which PM2 app is currently idle
+        current=$(grep "proxy_pass http://127.0.0.1:" /srv/www/production/my-repo-name/.config/.nginx/mydomain.com.conf | awk -F':' '{print $3}' | awk -F';' '{print $1}')
+        if [ "$current" == "3001" ]; then
+          active_app="blue"
+          active_port="3001"
+          idle_app="green"
+          idle_port="3002"
+        else
+          active_app="green"
+          active_port="3002"
+          idle_app="blue"
+          idle_port="3001"
+        fi
 
-          # start the idle app in preparation of the switch-over
-          ipm2 start [$idle_app]my-repo-name
+        # build the idle app - exit on failure
+        cd /srv/www/production/my-repo-name-$idle_app
+        git pull
+        npm install
+        if ! npm run build; then
+          echo "Build failed on my-repo-name-$idle_app."
+          exit 1
+        fi
 
-          # turn the idle app into the LIVE app
-          sudo sed -i 's/proxy_pass http:\/\/127.0.0.1:'"$active_port"'/proxy_pass http:\/\/127.0.0.1:'"$idle_port"'/g' /srv/www/.config/.nginx/sites-enabled/mydomain.com
-          sudo nginx -s reload
+        # start the idle app in preparation of the switch-over
+        pm2 start my-repo-name[$idle_app]
 
-          # stop the previously live, now idle, app
-          #  - preserves resources
-          #  - necessary to make the PM2 describe command work on next deployment)
-          ipm2 stop [$active_app]my-repo-name
-        '
+        # turn the idle app into the LIVE app
+        sudo sed -i 's|proxy_pass http://127.0.0.1:'"$active_port"'|proxy_pass http://127.0.0.1:'"$idle_port"'|g' /srv/www/production/my-repo-name/.config/.nginx/mydomain.com.conf
+        sudo nginx -s reload
+
+        # stop the previously live, now idle, app
+        #  - preserves resources
+        #  - necessary to make the PM2 describe command work on next deployment)
+        pm2 stop my-repo-name[$active_app]
+
+        # save config for when server restarts
+        pm2 save
+
+        echo "Post-Deplay Active Port: $idle_port"
+        echo "Post-Deploy Idle Port: $active_port"
+        SSHCONN
